import type { Metadata } from "next";
import { manrope } from "@/app/fonts";
import Header from "@/app/components/header/header";
import Footer from "@/app/components/footer/footer";
import AppLink from "@/components/app-link/app-link";
import "@/app/globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className}`}>
        <Header />
        <main className="main">{children}</main>
        <Footer />
        <AppLink />
      </body>
    </html>
  );
}
